[package]
name = "gatepup-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "gatepup"
path = "src/main.rs"

[dependencies]
gatepup-core.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
