[package]
name = "gatepup-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gatepup-config.workspace = true
gatepup-observability.workspace = true
tokio.workspace = true
hyper.workspace = true
hyper-util.workspace = true
http.workspace = true
http-body-util.workspace = true
bytes.workspace = true
serde.workspace = true
tracing.workspace = true
thiserror.workspace = true
arc-swap.workspace = true
tokio-rustls.workspace = true
hyper-rustls.workspace = true
rustls-pemfile.workspace = true
ipnet.workspace = true
async-compression.workspace = true
tokio-util.workspace = true
futures-util.workspace = true

[dev-dependencies]
gatepup-config.workspace = true
gatepup-observability.workspace = true
tokio.workspace = true
rcgen.workspace = true
flate2 = "1"
hyper.workspace = true
hyper-util.workspace = true
http.workspace = true
http-body-util.workspace = true
bytes.workspace = true
